language: c
sudo: required
dist: trusty

before_install:
    - "sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science dvipng"

script:
  - |
    make


